### ISSUE TITLE
This doesn't actually work yet...

### ISSUE THREAD

**Issue by fryfrog** [fryfrog/unifi-protect#1]
This doesn't work yet and I'll keep track of my progress here...

**Comment by fryfrog** [comment]
![chrome_1sBoKW4TKB](https://user-images.githubusercontent.com/87748/57004624-3d9c8100-6b85-11e9-880d-db926f7fa960.png)

At this point, I set the name and create an account, but it sits there doing this and spewing to logs.

**Comment by fryfrog** [comment]
Since it uses many of the same ports as unifi-video, I stopped my Docker container for that and fired this one up w/ *all* the ports on their Protect ports page correctly set on the right ports. It didn't help.

Next idea is going to be copying the data folder from the working VM, see if that works. Then undo that and try copying just the DB from the working VM. Then copy both, at least narrow down where to look.

**Comment by fryfrog** [comment]
I'm poking around w/ storing the db externally (which we need to do otherwise its fucked), but running into issues of `postgres` user (and uid).

**Comment by fryfrog** [comment]
I've moved this to an Ubuntu + S6 overlay to make running multiple processes (protect and postgres) inside. I've also made the package install at *startup* to force feeding it via url or file, in case Ubiquity wants to make it not exist easily.

I've also made the db config and db folder external, installing postgress as part of startup too because the post install script is what creates the initial db and protect uses *that* db instead of its own. :/

It still isn't working though.

**Comment by fryfrog** [comment]
![Screen Shot 2019-05-02 at 1 23 36 PM](https://user-images.githubusercontent.com/87748/57104690-e1994000-6cdd-11e9-9e9d-0a5343b93511.png)

I've deleted the Docker hub, but I'll keep this repo around just because.

**Comment by johntdyer** [comment]
Thank you for keeping this !

**Comment by fryfrog** [comment]
![Screen Shot 2019-05-02 at 1 46 39 PM](https://user-images.githubusercontent.com/87748/57105829-ba903d80-6ce0-11e9-87e3-06a7cc0e24da.png)

There was also this, so I'd expect even if you *have* the `.deb` to install, it just flat out won't work at some point.

**Comment by fryfrog** [comment]
Looks like they've let v1.12.5 into the wild, so I've re-enabled it on Docker Hub and have started poking around w/ it again. Still works fine in a VM, but in Docker it gets stuck at the same thing. :)

**Comment by glahera** [comment]
I've got  a fork I've done this morning, but so far I'm stuck with running it since it seems to depend on some private nodejs repo  @ubnt. Also it seems to have deprecated connection with Postgresql.

**Comment by fryfrog** [comment]
FWIW, I can install *just* the `.deb` file on an Ubuntu 18.04 VM and it works fine, so it clearly isn't pulling anything in from their own repos. In my Dockerfile, when it installs the `.deb`, it also pulls in postgresql and a few other things. It *runs* and I can see it doing stuff. It kind of seems like the logs are showing things trying to connect to the `172.x.x.x` network that Docker uses, so maybe a port forward is missing?

I'm trying to get a macvlan working so it can have its very own IP, but must be doing something wrong there.

**Comment by glahera** [comment]
I see.... Let me check some stuffs real quick then.

**Comment by fryfrog** [comment]
Are you using my Dockerfile or do you have your own custom one? If you have a custom one, can you link it for me to look at?

**Comment by glahera** [comment]
Here's my current image:
https://pastebin.com/LfW0Z7Sf

**Comment by glahera** [comment]
I tried with bionic VM, it is definitely not working.
![Capture](https://user-images.githubusercontent.com/22131815/66855469-90c38e00-ef83-11e9-9789-068599e36ff4.PNG)

**Comment by fryfrog** [comment]
Ah, don't just `dkpk` install it. Try `apt install ./package.deb` instead, that'll install all the deps like nodejs and postgresql. And you probably want to be using the `unifi-protect.service` file via `systemctl` instead of what ever script you're running.

**Comment by glahera** [comment]
That is the script generated by the deb itself

**Comment by fryfrog** [comment]
I figured, but they don't start it that way... they have a bunch of stuff in their environment setup by the systemd `.service` file.

**Comment by glahera** [comment]
Still doesn't work....
![image](https://user-images.githubusercontent.com/22131815/66856213-02e8a280-ef85-11e9-8043-da7bec1fa2a9.png)

**Comment by glahera** [comment]
On `top`  I found that sometime a process named  `unifi-protect` does appear but really inconsistent

**Comment by fryfrog** [comment]
Holy shit, it works w/ macvlan!
